# Generated by Django 5.1.4 on 2024-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0002_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
