# Generated by Django 5.1.4 on 2024-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0003_userpermissions_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='file_assigned_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='file_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
