# Generated by Django 5.1.4 on 2024-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0004_user_remove_userpermissions_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
