# Generated by Django 5.1.4 on 2024-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0005_user_email_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
