# Generated by Django 5.1.4 on 2024-12-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0007_shareablelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanagerapp.user'),
        ),
    ]
