# Generated by Django 5.1.4 on 2024-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0009_remove_shareablelink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='permission_Type',
            field=models.CharField(default='view', max_length=255),
        ),
    ]
