# Generated by Django 5.1.4 on 2024-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0010_userpermissions_permission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareablelink',
            name='can_view',
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='can_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shareablelink',
            name='max_downloads',
            field=models.IntegerField(default=5),
        ),
    ]
