# Generated by Django 5.1.4 on 2024-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0011_remove_shareablelink_can_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='encryption_key',
            field=models.TextField(null=True),
        ),
    ]
