# Generated by Django 5.1.4 on 2024-12-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0012_encryptedfile_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareablelink',
            name='can_download',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='can_preview',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='current_downloads',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='max_downloads',
        ),
    ]
