# Generated by Django 5.1.4 on 2024-12-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0013_remove_shareablelink_can_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='authTag',
            field=models.TextField(null=True),
        ),
    ]
