# Generated by Django 5.1.4 on 2024-12-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagerapp', '0015_totpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
